{% set name = "exoplanet" %}
{% set version = "0.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 821789b6f26eee978e8757a0074377d53e4c9795ca8afd1c598f1f3cf29bf455

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install .  --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - numpy
    - pybind11 >=2.4
    - setuptools >=0.7.0
    - setuptools_scm >=1.15
  run:
    - python
    - theano >=1.0.4
    - {{ pin_compatible('numpy') }}
    - pymc3 >=3.8
    - astropy >=3.1
    - pymc3-ext >=0.0.1

test:
  imports:
    - exoplanet

about:
  home: https://exoplanet.dfm.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Fast and scalable MCMC for all your exoplanet needs
  description: |
    exoplanet is a toolkit for probabilistic modeling of transit and/or radial
    velocity observations of exoplanets and other astronomical time series using
    PyMC3. PyMC3 is a flexible and high-performance model building language and
    inference engine that scales well to problems with a large number of
    parameters. exoplanet extends PyMC3's language to support many of the custom
    functions and distributions required when fitting exoplanet datasets.
  doc_url: https://exoplanet.dfm.io
  dev_url: https://github.com/dfm/exoplanet

extra:
  recipe-maintainers:
    - dfm
    - rodluger
