{% set name = "exoplanet" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bfd744f0e1008589eed00611a770a29009245ba74ccca06567ccc17183dca5ac

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install .  --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools >=40.6.0
    - wheel
    - setuptools_scm >=1.15
  run:
    - python >=3.9
    - exoplanet-core >=0.3.0
    - pymc >=5.0.0
    - astropy >=3.1

test:
  imports:
    - exoplanet

about:
  home: https://docs.exoplanet.codes
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Fast and scalable MCMC for all your exoplanet needs
  description: |
    exoplanet is a toolkit for probabilistic modeling of transit and/or radial
    velocity observations of exoplanets and other astronomical time series using
    PyMC3. PyMC3 is a flexible and high-performance model building language and
    inference engine that scales well to problems with a large number of
    parameters. exoplanet extends PyMC3's language to support many of the custom
    functions and distributions required when fitting exoplanet datasets.
  doc_url: https://docs.exoplanet.codes
  dev_url: https://github.com/exoplanet-dev/exoplanet

extra:
  recipe-maintainers:
    - dfm
    - rodluger
    - mwcraig
