{% set name = "exoplanet" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5e019d1721767b1d2c91137c18a7dc994a95350947f5cf457e7df52772e1fd2b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install .  --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=0.7.0
    - setuptools_scm >=1.15
  run:
    - python
    - theano >=1.0.4
    - numpy >=1.13.0
    - pymc3 >=3.5
    - astropy >=3.1

test:
  imports:
    - exoplanet

about:
  home: https://exoplanet.dfm.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Fast and scalable MCMC for all your exoplanet needs
  description: |
    exoplanet is a toolkit for probabilistic modeling of transit and/or radial
    velocity observations of exoplanets and other astronomical time series using
    PyMC3. PyMC3 is a flexible and high-performance model building language and
    inference engine that scales well to problems with a large number of
    parameters. exoplanet extends PyMC3's language to support many of the custom
    functions and distributions required when fitting exoplanet datasets.
  doc_url: https://exoplanet.dfm.io
  dev_url: https://github.com/dfm/exoplanet

extra:
  recipe-maintainers:
    - dfm
    - rodluger
